### ISSUE TITLE
Sometimes, a preview is not created

### ISSUE THREAD

**Issue by OgDInstant** [techlib/indoktrinator#18] opened 2017-04-20 11:22 UTC
Preview not created when adding MP4 to playlist test_udalost.

**Comment by mordae** [comment] 2017-04-25 10:05
Please re-check with new Harvester code. I was not able to reproduce this, though.

**Comment by ZtF** [comment] 2017-05-04 08:39
Tested and still not solved. I can provide video file that causes this issue.

**Comment by mordae** [comment] 2017-05-05 08:38
Fixed now.

**Closed as completed by mordae** 2017-05-05 08:38 UTC
Labels: bug
